workflows:
    react-native-ios:
        name: React Native iOS
        max_build_duration: 120
        instance_type: mac_mini_m1
        integrations:
          app_store_connect: CM-DNS
        environment:
          ios_signing:
            distribution_type: app_store
            bundle_identifier: "com.avh.nufm"
          vars:
            XCODE_WORKSPACE: "com.avh.nufm" # <-- Put the name of your Xcode workspace here
            XCODE_SCHEME: "nufmmobile" # <-- Put the name of your Xcode scheme here
            APP_ID: 6446584670 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
          node: v18.12.1
          xcode: latest
          cocoapods: default
        scripts:
            - name: Install npm dependencies
              script: |
                npm install
            - name: Set Info.plist values
              script: |
                # This allows publishing without manually answering the question about encryption 
                PLIST=$CM_BUILD_DIR/$XCODE_SCHEME/Info.plist
                PLIST_BUDDY=/usr/libexec/PlistBuddy
                $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST
            - name: Set up code signing settings on Xcode project
              script: |
                xcode-project use-profiles --warn-only
        artifacts:
            - build/ios/ipa/*.ipa
            - /tmp/xcodebuild_logs/*.log
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
       
