export const Login = {
  LOGIN: "LOGIN",
  LOGIN_START: "LOGIN_START",
  LOGIN_END: "LOGIN_END",
  LOGIN_FAIL: "LOGIN_FAIL",
};

//Worker
export const GetWorkers = {
  GETWORKERS_START: "GETWORKERS_START",
  GETWORKERS_END: "GETWORKERS_END",
  GETWORKERS_FAIL: "GETWORKERS_FAIL",
};

export const AddWorker = {
  ADD_WORKER: "ADD_WORKER",
  ADD_WORKER_START: "ADD_WORKER_START",
  ADD_WORKER_END: "ADD_WORKER_END",
  ADD_WORKER_FAIL: "ADD_WORKER_FAIL",
};

//Attendance
export const GetAttendances = {
  GET_ATTENDANCES: "GET_ATTENDANCES_",
  GET_ATTENDANCES_START: "GET_ATTENDANCES_START",
  GET_ATTENDANCES_END: "GET_ATTENDANCES_END",
  GET_ATTENDANCES_FAIL: "GET_ATTENDANCES_FAIL",
};

export const GetCheckById = {
  GET_CHECK_BY_ID_END: "GET_CHECK_BY_ID_END",
  GET_CHECK_BY_ID_FAIL: "GET_CHECK_BY_ID_FAIL",
};

//Fcaility
export const GetFacilities = {
  GET_FACILITIES_START: "GET_FACILITIES_START",
  GET_FACILITIES_END: "GET_FACILITIES_END",
  GET_FACILITIES_FAIL: "GET_FACILITIES_FAIL",
};

export const AddFacility = {
  ADD_FACILITY: "ADD_FACILITY",
  ADD_FACILITY_END: "ADD_FACILITY_END",
  ADD_FACILITY_START: "ADD_FACILITY_START",
  ADD_FACILITY_FAIL: "ADD_FACILITY_FAIL",
};

export const GetAllParent = {
  GET_ALL_PARENT_START: "GET_ALL_PARENT_START",
  GET_ALL_PARENT_END: "GET_ALL_PARENT_END",
  GET_ALL_PARENT_FAIL: "GET_ALL_PARENT_FAIL",
};

//Risk
export const GetRisks = {
  GET_RISKS_START: "GET_RISKS_START",
  GET_RISKS_END: "GET_RISKS_END",
  GET_RISKS_FAIL: "GET_RISKS_FAIL",
};

export const GetRiskDetails = {
  GET_RISK_DETAILS_END: "GET_RISK_DETAILS_END",
  GET_RISK_DETAILS_FAIL: "GET_RISK_DETAILS_FAIL",
};

//Incidents
export const GetIncidents = {
  GET_INCIDENTS_START: "GET_INCIDENTS_START",
  GET_INCIDENTS_END: "GET_INCIDENTS_END",
  GET_INCIDENTS_FAIL: "GET_INCIDENTS_FAIL",
};

export const GetIncidentDetails = {
  GET_INCIDENT_DETAILS_END: "GET_INCIDENT_DETAILS_END",
  GET_INCIDENT_DETAILS_FAIL: "GET_INCIDENT_DETAILS_FAIL",
};

//Notification
export const GetNotifications = {
  GET_NOTIFICATIONS_START: "GET_NOTIFICATIONS_START",
  GET_NOTIFICATIONS_END: "GET_NOTIFICATIONS_END",
  GET_NOTIFICATIONS_FAIL: "GET_NOTIFICATIONS_FAIL",
};
export const GetNotificationDetails = {
  GET_NOTIFICATION_DETAILS_END: "GET_NOTIFICATION_DETAILS_END",
  GET_NOTIFICATION_DETAILS_FAIL: "GET_NOTIFICATION_DETAILS_FAIL",
};

//Order
export const GetOrders = {
  GET_ORDERS_START: "GET_ORDERS_START",
  GET_ORDERS_END: "GET_ORDERS_END",
  GET_ORDERS_FAIL: "GET_ORDERS_FAIL",
};

export const GetOrderDetails = {
  GET_ORDER_DETAILS_END: "GET_ORDER_DETAILS_END",
  GET_ORDER_DETAILS_FAIL: "GET_ORDER_DETAILS_FAIL",
};

export const AddOrder = {
  ADD_ORDER: "ADD_ORDER",
  ADD_ORDER_START: "ADD_ORDER_START",
  ADD_ORDER_END: "ADD_ORDER_END",
  ADD_ORDER_FAIL: "ADD_ORDER_FAIL",
};
