export const GetWorkers = {
  GETWORKERS: "GETWORKERS",
  GETWORKERS_START: "GETWORKERS_START",
  GETWORKERS_END: "GETWORKERS_END",
  GETWORKERS_FAIL: "GETWORKERS_FAIL",
};

export const AddWorker = {
  ADD_WORKER: "ADD_WORKER",
  ADD_WORKER_START: "ADD_WORKER_START",
  ADD_WORKER_END: "ADD_WORKER_END",
  ADD_WORKER_FAIL: "ADD_WORKER_FAIL",
};

export const GetAttendances = {
  GET_ATTENDANCES: "GET_ATTENDANCES_",
  GET_ATTENDANCES_START: "GET_ATTENDANCES_START",
  GET_ATTENDANCES_END: "GET_ATTENDANCES_END",
  GET_ATTENDANCES_FAIL: "GET_ATTENDANCES_FAIL",
};

export const GetCheckById = {
  GET_CHECK_BY_ID_END: "GET_CHECK_BY_ID_END",
  GET_CHECK_BY_ID_FAIL: "GET_CHECK_BY_ID_FAIL",
};
